.TH listbucket 1 "December 2016" Moray "Moray Client Tools"
.SH NAME
.PP
listbucket \- print detailed information about all buckets
.SH SYNOPSIS
.PP
\fB\fClistbucket [COMMON_OPTIONS]\fR
.SH DESCRIPTION
.PP
Fetches a JSON representation for the configuration of all buckets on the remote
server.  See \fB\fCgetbucket(1)\fR for details about this representation.
.SH OPTIONS
.PP
See \fB\fCmoray(1)\fR for information about the \fB\fCCOMMON_OPTIONS\fR, which control
the log verbosity and how to locate the remote server.
.SH ENVIRONMENT
.PP
See \fB\fCmoray(1)\fR for information about the \fB\fCLOG_LEVEL\fR, \fB\fCMORAY_SERVICE\fR, and
\fB\fCMORAY_URL\fR environment variables.
.SH EXAMPLES
.SH SEE ALSO
.PP
\fB\fCmoray(1)\fR, \fB\fCgetbucket(1)\fR, \fB\fCputbucket(1)\fR
